name: Deploy Frontend
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t balsa823/complex-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true balsa823/complex-test npm test -- --coverage

      - run: docker build -t balsa823/complex-client ./client
      - run: docker build -t balsa823/complex-nginx ./nginx
      - run: docker build -t balsa823/complex-server ./server
      - run: docker build -t balsa823/complex-worker ./worker
 
      - run: docker push balsa823/complex-client
      - run: docker push balsa823/complex-nginx
      - run: docker push balsa823/complex-server
      - run: docker push balsa823/complex-worker
 
      - name: Generate deployment package
              run: zip -r deploy.zip . -x '*.git*'
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          application_name: complex
          environment_name: Complex-env
          existing_bucket_name: elasticbeanstalk-us-east-2-781269532038
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip